version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend_app
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend_app
      - /backend_app/node_modules # prevent overwriting node_modules inside container
      - ./backend/mydatabase.db:/backend_app/mydatabase.db  # 👈 mounts the DB file directly from local only temporary  
    working_dir: /backend_app
    command: npm run dev
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  frontend:
    build:
      context: ./frontend
    container_name: frontend_app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend_app
      - /frontend_app/node_modules  # same for frontend
    working_dir: /frontend_app
    command: npm run dev -- --host
    depends_on:
      - backend
    restart: unless-stopped